const axios = require('axios');

async function generateCryptoReport() {
  const currentDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const prompt = `Generate a daily cryptocurrency tracking report formatted for Notion with rich visuals and emojis. Format the report EXACTLY as shown below:

# 📊 AIXBT Crypto Tracker Report
**📅 Date:** ${currentDate}

## 📈 Price Predictions & Trading Signals

**🚨 CRITICAL REQUIREMENT: Use LIVE/REAL-TIME prices from CoinGecko.com or CoinMarketCap.com API data. DO NOT use outdated or hypothetical prices.**

Create a comprehensive analysis table for each cryptocurrency with these columns:

### 🪙 Primary Cryptocurrencies Analysis

For each coin, provide this structured format:

**Bitcoin (BTC)** 🟠
- 💵 **Current Price:** $[REAL-TIME PRICE from CoinGecko/CMC]
- 🔮 **30D Target:** $[predicted price]
- 📌 **Short-Term Action:** ✅ BUY / ❌ SELL / ⏸️ HOLD
- 🧩 **ST Justification:** [Based on tracked accounts insights - 2-3 sentences]
- 🚀 **6M Target:** $[predicted price] 
- 🔒 **Long-Term Action:** ✅ BUY / ❌ SELL / ⏸️ HOLD
- 🧩 **LT Justification:** [Based on fundamental analysis - 2-3 sentences]

**Ethereum (ETH)** 🔵
[Same format as above]

**Solana (SOL)** 🟣
[Same format as above]

Continue this format for: NEAR, ICP, CRV, HIVE, AVAX, LINK, DOGE, FLOKI, ADA

### 🌟 Additional High-Potential Tokens
Select 5 promising tokens from top 100 market cap and analyze using the same format.

### 📰 Key Market Insights from Tracked Accounts

**🐋 Whale Activity:**
- [Summarize major whale movements and institutional flows]

**📊 On-Chain Data:**
- [Key on-chain metrics and trends]

**💬 Sentiment Analysis:**
- [Overall market sentiment from tracked accounts]

**🔥 Trending Narratives:**
- [Hot topics and emerging trends]

## 📌 How to Use This Tracker

**Short-Term (30 Days)** ⚡
- ✅ **BUY:** Strong momentum, positive catalysts expected
- ❌ **SELL:** Bearish signals, potential short-term decline
- ⏸️ **HOLD:** Mixed signals, wait for clearer direction

**Long-Term (6 Months)** 🎯
- ✅ **BUY:** Strong fundamentals, adoption growth expected
- ❌ **SELL:** Fundamental concerns, competitive threats
- ⏸️ **HOLD:** Stable outlook, limited upside/downside

## ⚠️ Important Disclaimers

**🔍 Data Sources:** Real-time prices from CoinGecko.com and CoinMarketCap.com
**📱 Social Intelligence:** Insights aggregated from @aixbt_agent, @OnchainDataNerd, @ASvanevik, @DefiIgnas, @simononchain, @zachxbt, @lookonchain, @WuBlockchain, @0xngmi, @CryptoHayes, @CryptoKaleo, @Pentosh1, @stacy_muur, @MikybullCrypto, @CryptoGirlNova, @0xbeinginvested, @ChainROI, @100xDarren, @Chyan, @cryptorinweb3

**🚨 Risk Warning:** This analysis is for educational purposes only and NOT financial advice. Cryptocurrency markets are highly volatile and unpredictable. Always conduct your own research (DYOR) before making any investment decisions.

---
*🤖 Generated by AIXBT Tracker System | ${new Date().toLocaleString()} UTC*

### 🔥 CRITICAL INSTRUCTIONS FOR GROK AI:

1. **MANDATORY:** Fetch current prices from CoinGecko.com or CoinMarketCap.com APIs - DO NOT use old cached data
2. **MANDATORY:** Base all predictions on recent posts and sentiment from the specified Twitter accounts
3. **MANDATORY:** Use the exact emoji formatting shown above for visual appeal in Notion
4. **MANDATORY:** Provide specific, actionable insights rather than generic statements
5. **MANDATORY:** Include concrete price targets based on technical and sentiment analysis

**PRICE ACCURACY IS CRITICAL** - Verify all current prices are from live market data sources.`;

  try {
    console.log('🤖 Calling Grok AI API...');
    
    // Test API connectivity first
    const testResponse = await testGrokAPI();
    if (!testResponse.success) {
      console.log('⚠️ API connectivity issues, generating fallback report');
      return generateFallbackReport(currentDate);
    }

    // Latest Grok models for 2025 - prioritizing newest versions
    const possibleModels = [
      'grok-4',           // Latest Grok 4
      'grok-4-latest',    // Latest version
      'grok-3',           // Grok 3
      'grok-3-latest',    // Latest Grok 3
      'grok',             // Generic alias
      'grok-latest'       // Latest available
    ];
    
    let response = null;
    let lastError = null;

    for (const model of possibleModels) {
      try {
        console.log(`Trying model: ${model}`);
        
        response = await axios.post('https://api.x.ai/v1/chat/completions', {
          messages: [
            {
              role: "system",
              content: "You are the AIXBT advanced cryptocurrency tracking system with MANDATORY access to real-time market data from CoinGecko.com and CoinMarketCap.com APIs. You MUST fetch current live prices - never use outdated or cached data. You analyze insights from top crypto Twitter accounts: @aixbt_agent, @OnchainDataNerd, @ASvanevik, @DefiIgnas, @simononchain, @zachxbt, @lookonchain, @WuBlockchain, @0xngmi, @CryptoHayes, @CryptoKaleo, @Pentosh1, @stacy_muur, @MikybullCrypto, @CryptoGirlNova, @0xbeinginvested, @ChainROI, @100xDarren, @Chyan, and @cryptorinweb3. Provide accurate price predictions and trading signals based on CURRENT market data and RECENT sentiment analysis from these influencers. Format your response as a visually appealing Notion-ready report with proper emojis and rich formatting. CRITICAL: All current prices MUST be fetched from live market APIs - price accuracy is your highest priority."
            },
            {
              role: "user", 
              content: prompt
            }
          ],
          model: model,
          max_tokens: 4000,
          temperature: 0.7,
          stream: false
        }, {
          headers: {
            'Authorization': `Bearer ${process.env.GROK_API_KEY}`,
            'Content-Type': 'application/json',
            'User-Agent': 'AIXBT-Tracker/1.0'
          },
          timeout: 60000,
          validateStatus: function (status) {
            return status < 500; // Resolve only if status is less than 500
          }
        });

        // Check if response is successful
        if (response.status === 200 && response.data?.choices?.[0]?.message?.content) {
          console.log(`✅ Successfully used model: ${model}`);
          const report = response.data.choices[0].message.content;
          console.log(`✅ Generated report: ${report.length} characters`);
          return report;
        } else {
          throw new Error(`Invalid response: ${response.status} - ${JSON.stringify(response.data)}`);
        }

      } catch (error) {
        console.log(`❌ Model ${model} failed:`, error.response?.status || error.message);
        lastError = error;
        continue;
      }
    }

    // If all models failed, provide detailed fallback
    console.error('❌ All Grok models failed. Generating comprehensive fallback report...');
    return generateFallbackReport(currentDate, lastError);
    
  } catch (error) {
    console.error('❌ Error generating report with Grok:', error.message);
    return generateFallbackReport(currentDate, error);
  }
}

async function testGrokAPI() {
  try {
    const response = await axios.get('https://api.x.ai/v1/models', {
      headers: {
        'Authorization': `Bearer ${process.env.GROK_API_KEY}`,
        'Content-Type': 'application/json'
      },
      timeout: 10000
    });
    
    if (response.status === 200) {
      console.log('✅ Grok API connectivity confirmed');
      console.log('📋 Available models:', response.data.data?.map(m => m.id).join(', ') || 'Unknown');
      return { success: true, models: response.data.data };
    } else {
      return { success: false, error: `Status: ${response.status}` };
    }
  } catch (error) {
    console.log('⚠️ Grok API connectivity test failed:', error.message);
    return { success: false, error: error.message };
  }
}

function generateFallbackReport(currentDate, error = null) {
  const errorDetails = error ? `\n**⚠️ Error Details:** ${error.response?.status || error.message}` : '';
  
  return `# 📊 AIXBT Crypto Tracker Report
**📅 Date:** ${currentDate}

## 🔧 System Status Notice
The automated Grok AI analysis is temporarily unavailable. Operating in backup mode with manual oversight.${errorDetails}

## 📈 Market Overview Status

**🟠 Bitcoin (BTC)**
- 💵 **Status**: 🟡 Monitor - Technical analysis pending  
- 📊 **Note**: Core digital asset, watch key support/resistance levels
- 🎯 **Action**: Manual analysis required for current positioning

**🔵 Ethereum (ETH)** 
- 💵 **Status**: 🟢 Active Development
- 📊 **Note**: Ongoing network improvements and DeFi ecosystem growth
- 🎯 **Action**: Monitor development updates and institutional adoption

**🟣 Solana (SOL)**
- 💵 **Status**: ⚡ High Ecosystem Activity  
- 📊 **Note**: Continued ecosystem expansion with new projects launching
- 🎯 **Action**: Track ecosystem developments and TVL growth

### 🌟 Additional Major Assets Status

**🪙 Primary Holdings:**
- **ADA** 🔵: Regular development updates, steady progress on roadmap
- **AVAX** 🔴: Infrastructure development ongoing, subnet adoption
- **LINK** 🔗: Oracle network expansion, institutional partnerships  
- **NEAR** 🌈: Protocol development active, AI integration focus
- **ICP** 🟦: Internet Computer platform updates, Web3 adoption
- **CRV** 💙: DeFi protocols evolution, Curve ecosystem growth
- **HIVE** 🟨: Decentralized content platform, community building
- **DOGE** 🟡: Community-driven momentum, payment integration
- **FLOKI** 🐕: Meme token ecosystem development, utility expansion

## 🔄 System Recovery Actions

**🛠️ Current Status:**
1. **API Monitoring**: Continuously checking Grok API availability  
2. **Backup Systems**: Manual market oversight and data collection active
3. **Recovery Timeline**: Automated AI analysis will resume when API connectivity is restored
4. **Data Sources**: Monitoring alternative feeds and social sentiment manually

## 📊 General Market Guidance

While automated AI analysis is temporarily unavailable:

**📈 Technical Analysis:**
- Monitor major support/resistance levels across primary assets
- Watch trading volume patterns for trend confirmation  
- Track institutional flows and whale movements

**🐦 Social Sentiment:**
- Follow key crypto Twitter accounts for real-time insights
- Monitor on-chain data providers for fundamental metrics
- Watch for narrative shifts and emerging trends

**⚡ Risk Management:**
- Use multiple data sources for decision making
- Maintain appropriate position sizing
- Set clear entry/exit criteria

## ⚠️ Important Disclaimers

**🚨 System Status**: This is a maintenance report during API service restoration
**📊 Data Accuracy**: Manual collection and oversight currently active  
**💡 Not Financial Advice**: All information for educational purposes only
**🔥 Market Volatility**: Cryptocurrency markets remain highly volatile
**🔄 Service Recovery**: Full automated AI analysis will resume shortly

## 🛠️ Technical Notes

- **System**: Automated report generation temporarily operating in backup mode
- **Timeline**: Working to restore full AI-powered functionality  
- **Contact**: System administrators have been notified and are actively resolving
- **Updates**: Service status will be communicated through normal channels

---
*🤖 Generated by AIXBT Tracker Backup System - ${new Date().toLocaleString()} UTC*
*⚡ Full AI-powered analysis with live price feeds will resume once API connectivity is restored*

**🔥 Priority Action Items:**
1. ✅ Verify API key permissions for latest Grok models
2. ✅ Test connectivity with updated model endpoints  
3. ✅ Confirm real-time price feed integration
4. ⏳ Resume automated daily report generation`;
}

module.exports = { generateCryptoReport };
